### ISSUE TITLE
Should we disable vFlash SD card on new hardware?

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#871] opened 2023-03-30 19:29 UTC
Looks like the new oct4 hardware has SD card to boot from, and it's first in the boot order. 

So, when ironic inspects a node
```
(overcloud) [stack@localhost ~]$ openstack baremetal node show oct4-cha3-3c -f json | jq .properties.local_gb
"13"
```
it reports only that disk and hides any other "real" drives. I think if all our servers have dual 120G SSD then we might as well disable the sd card instead of just lowering it in the boot order. Also, for most use cases a 13 GB boot drive maybe barely enough. @hakasapl thoughts?

**Comment by naved001** [comment] 2023-03-30 19:30
It may be possible to disable it form the lifecycle controller or using the racadm command line. 

https://www.dell.com/support/manuals/en-us/idrac8-with-lc-v2.05.05.05/lc_2.05.05.05_ug-v1/enabling-or-disabling-a-vflash-sd-card?guid=guid-194ffa01-2642-4159-9350-382b1aadcef6&lang=en-us

For iDrac9; https://www.dell.com/support/manuals/en-us/idrac9-lifecycle-controller-v3.3-series/idrac_3.30.30.30_ug/enabling-or-disabling-vflash-functionality?guid=guid-f5a95a32-fa42-448b-8c31-5f1b2b2b4b39&lang=en-us

**Comment by hakasapl** [comment] 2023-03-30 20:54
Is this sd card virtually used through the idrac? If so it should probably be just moved down the load order. Otherwise, we should disable it if the bios lets us. I will do some digging in the idrac...

**Comment by hakasapl** [comment] 2023-04-03 19:08
I've disabled the vFlash on `OCT4-CHA3-1A`. @naved001 does that node inspect correctly now?

**Comment by tzumainn** [comment] 2023-04-06 13:36
I tested inspection on the node, and had the same result.

**Comment by joachimweyl** [comment] 2023-04-07 12:30
@hakasapl shall we try moving it down the boot order?

**Comment by hakasapl** [comment] 2023-04-07 14:50
@tzumainn when you say the same result, do you mean the inspection still sees the SD card only on `OCT4-CHA3-1A`?

**Comment by tzumainn** [comment] 2023-04-07 15:08
Ah, I mean that inspection still results in the same values set in 'properties' for the node, so we see local_gb as 13

**Comment by joachimweyl** [comment] 2023-04-14 13:10
@hakasapl since the way in which we disabled vFlash on `OCT4-CHA3-1A` does not appear to have removed the local_gb of 13, what are the next steps?

**Comment by hakasapl** [comment] 2023-04-14 15:58
I would like to reproduce on my end and troubleshoot further, I'll likely do that next week

**Comment by tzumainn** [comment] 2023-04-21 15:20
Derek Higgins just showed me a way to handle this:

 openstack baremetal node set oct4-cha4-1a --property root_device='{"hctl": "1:0:0:0"}'

After running this and re-running inspection, the local_gb is now 185, so I think this solution works! I'll update the other oct4-cha4* nodes.

**Comment by tzumainn** [comment] 2023-04-21 18:09
Update: some of the nodes failed with that device hint, but all pass inspection with:

```
openstack baremetal node set <NODE> --property root_device='{"size": ">= 50"}'
```

**Comment by tzumainn** [comment] 2023-04-21 18:16
Closing this issue!

**Closed by tzumainn** 2023-04-21 18:16 UTC
Labels: added_post_planning
