### ISSUE TITLE
Move netbox to AWS EC2

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1200] opened 2023-12-13 16:39 UTC
We want to host netbox outside of MGHPCC so it is available 24/7. The burstable x86 instances seem like the best option for this, specifically `t3.large`. Using the EC2 savings plan we can prepay for a year of use in `t3` for ~450. This saves a good amount of money compared to paying month-to-month.

@msdisme will figure out if we can do this through BU AWS

@hakasapl will deploy on AWS once the above is set

**Comment by hakasapl** [comment] 2024-01-02 19:25
@msdisme is it possible to figure out he BU part of this during this sprint? No worries if it needs to be pushed back, I'd like to get it deployed in January if possible.

**Comment by hakasapl** [comment] 2024-01-02 19:56
Sorry - by this sprint I meant the sprint that starts tomorrow

**Comment by msdisme** [comment] 2024-03-06 02:49
@hakasapl if needed this sprint (March 6-27) please move it over during planning.

**Comment by msdisme** [comment] 2024-06-03 19:31
@hakasapl should we close as a duplicate of https://github.com/nerc-project/operations/issues/582

**Closed** 2024-07-24 14:38 UTC
Labels: blocked
