### ISSUE TITLE
Inventory spare hardware at MGHPCC

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#590] opened 2022-06-06 17:37 UTC
It would be nice to have a document of what we have at the data center so any maintenance tasks can move forwardly smoothly.

We should also compile a list of servers that don't function and figure out if it's possible to use them for spare parts (and what parts are actually useful).

**Comment by joachimweyl** [comment] 2022-07-01 13:27
@hakasapl is this done or do you still have some items you want to inventory today?

**Comment by hakasapl** [comment] 2022-07-01 14:01
The inventory is done but I am working on cleaning up the spreadsheet and ordering spare parts.

**Comment by hakasapl** [comment] 2022-07-05 20:15
Duplicate of https://github.com/CCI-MOC/ops-issues/issues/611

**Closed by hakasapl** 2022-07-05 20:15 UTC
Labels: mghpcc, accepted, size/small
