### ISSUE TITLE
Secure serial console access in ESI

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#1291] opened 2024-04-12 19:12 UTC
Something in the short term because right now serial console, if enabled by the user, can be accessed from anywhere in the world without any authentication.

Long term solution being discussed here: https://github.com/CCI-MOC/esi/issues/533

**Comment by tzumainn** [comment] 2024-04-12 19:17
Short-term, the only solutions I can think of are to either disable console usage, or to warn users to disable the console as soon as they're done using it.

**Comment by tzumainn** [comment] 2024-04-12 19:35
In the mid-short term, I think we could advance the shellinabox/web proxy solution.

**Comment by tzumainn** [comment] 2024-08-21 14:42
Closing as a duplicate of the more fine-grained https://github.com/CCI-MOC/esi/issues/568

**Closed** 2024-08-21 14:54 UTC
