### ISSUE TITLE
mail problems with AWS

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#206] opened 2021-03-16 15:42 UTC
Query from AWS: What type of configuration or setup have you implemented to prevent spam from originating from your Ec2 resource?

**Comment by msdisme** [comment] 2021-03-16 15:44
-access primarily via mailing lists - they all have moderators who must review/approve before sending occurs
-mailing lists include a mechanism to unsubscribe

**Comment by larsks** [comment] 2021-03-16 16:56
This isn't strictly true:

> -access primarily via mailing lists - they all have moderators who must review/approve before sending occurs

The lists are not necessarily all moderated (I don't know; I haven't checked), but they are configured to allow posting only by list members.

**Comment by msdisme** [comment] 2021-03-16 19:57
OK, have more details which unfortunately had been blocked by my spam filter: 

I will attach the details from the 2 emails with spam logs in a file - also, I'll figure out with these did not go to the admin list which forwards appropriately.

**Comment by msdisme** [comment] 2021-03-17 13:36
kumo-owner@lists.massopen.cloud - who owns, for example.

**Comment by larsks** [comment] 2021-03-17 13:40
When you see an address like `<listname>-owner`, that means it's an alias for the owner of the `<listname>` list. E.g., that email address goes to the owner of `kumo@lists.massopen.cloud`, which is @naved001.

**Comment by larsks** [comment] 2021-03-17 16:23
This was all a dupe of #204. Please put all new comments in that ticket.

**Closed by larsks** 2021-03-17 16:23 UTC
Labels: accepted
