### ISSUE TITLE
Order cables for oct 3

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#343] opened 2021-08-23 01:47 UTC
For the new switch that we will add to OCT3

**Comment by naved001** [comment] 2021-09-01 13:45
I will go to BU and sort all the 10G cables we have and put them in a box.

**Comment by naved001** [comment] 2021-09-15 21:28
Here's the inventory of cables.

https://docs.google.com/spreadsheets/d/1cluTx91eAQvRnrxwAJKyYO0J_bKcvhtq29SEMr-bgJc/edit#gid=0

**Comment by naved001** [comment] 2021-09-21 14:25
@hakasapl @msdisme pinging you guys so you can take a look at this and we can plan how to ship the cables that we have at BU.

**Comment by pjd-nu** [comment] 2021-09-21 16:15
If you need, I can eBay some more cables and have them delivered to Holyoke.

On Sep 21, 2021, at 10:25 AM, Naved Ansari ***@***.******@***.***>> wrote:



@hakasapl<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhakasapl&data=04%7C01%7Cp.desnoyers%40northeastern.edu%7Cf551263d0f584614326c08d97d0bb8a2%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C637678311564398312%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EYjWujhewLfR5vBmjLZJ8xruoX2TORbeY%2FZArMf5Dxc%3D&reserved=0> @msdisme<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmsdisme&data=04%7C01%7Cp.desnoyers%40northeastern.edu%7Cf551263d0f584614326c08d97d0bb8a2%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C637678311564398312%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LFL3Sxczl73w95xRe4isCYCzdcfM9nKq1B642WxMdPM%3D&reserved=0> pinging you guys so you can take a look at this and we can plan how to ship the cables that we have at BU.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCCI-MOC%2Fops-issues%2Fissues%2F343%23issuecomment-924041916&data=04%7C01%7Cp.desnoyers%40northeastern.edu%7Cf551263d0f584614326c08d97d0bb8a2%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C637678311564408273%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xhBMjLvPPPVURjDgPlxSG48JfKQ235mqW1%2FsflrHjTA%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA5Y5K4VWLKVIH2MR75OBK3UDCIXBANCNFSM5CTSHOCQ&data=04%7C01%7Cp.desnoyers%40northeastern.edu%7Cf551263d0f584614326c08d97d0bb8a2%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C637678311564408273%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1Jf6yWnYIBV4ZHEHSkpA%2FwhG1sxkKrpgfATgyv7B1so%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cp.desnoyers%40northeastern.edu%7Cf551263d0f584614326c08d97d0bb8a2%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C637678311564418223%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pkePOhifj5RhJ54rNpPLDUSpL5EIDJgSWDJEDsIA4TE%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cp.desnoyers%40northeastern.edu%7Cf551263d0f584614326c08d97d0bb8a2%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C637678311564418223%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Mb1mRp7LaO%2F4OJmiHbXL3ngG4IMXNW2%2FA73ze2nx1C4%3D&reserved=0>.

**Comment by naved001** [comment] 2021-09-21 16:52
@pjd-nu we haven't placed the order for the switch yet, so getting the cables delivered won't impact the overall timing.
@msdisme I am planning to meet @hakasapl this weekend since he'll be near Boston so he can pick up the cables.

**Comment by larsks** [comment] 2021-09-21 19:21
Closed as a dupe of #336

**Closed by larsks** 2021-09-21 19:21 UTC
Labels: accepted

**Comment by naved001** [comment] 2021-09-25 18:54
I handed over most cables, some intel SSDs, and 2 juniper 1gig switches to Hakan today. These will be put in the MOC cage at MGHPCC since we are now not limited to a single red box in bu cage. 

[This is the link](https://docs.google.com/spreadsheets/d/1cluTx91eAQvRnrxwAJKyYO0J_bKcvhtq29SEMr-bgJc/edit#gid=0) to the inventory, @hakasapl can double check that.

cc: @msdisme
