### ISSUE TITLE
Install GPU's (how many arrived) for use in SMAUG cluster. 

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#438] opened 2021-10-29 21:11 UTC
- [x] decide which systems to install these in
- [ ]  confirm date and update this ticket: https://github.com/operate-first/support/issues/147
- [ ] coordinate with Naved, Lars and Operate First team if this requires pulling any of the systems out of cluster
- [ ] update records with additions  
- [ ] add links to oct hardware details in kaizen spreadsheet-@naved may need to do this part due to permissions

**Comment by hakasapl** [comment] 2021-11-12 20:06
3 GPUs (Tesla P100s) have arrived

**Comment by msdisme** [comment] 2021-12-02 20:12
@naved001 suggests coolest, and Hakan concurs and will put them in top where the cables are least dense.  @larsks sound good to you, or any other operational/usage concerns to take into account.

**Comment by larsks** [comment] 2021-12-02 20:17
I defer to Hakan and Naved on this.

**Comment by msdisme** [comment] 2021-12-09 20:38
update based on various threads/discussions:
OCT 7 OCT General and Cloudlab-GPU’s there (~18 slolts free as of 12/9/21) R730’s

GPU's to OCT 7 due to need for larger chassis.

**Comment by cooktheryan** [comment] 2022-01-10 18:05
@msdisme is there any update on this?

**Comment by hakasapl** [comment] 2022-01-11 17:00
I will install these the week of the 24th (when I am back in the country) but the nodes themselves may be unavailable for another week due to the need to setup the upstream switching which is currently not set up.

**Comment by msdisme** [comment] 2022-01-25 16:39
Bumped this higher- hoping you can get them at least installed this week.

**Comment by hakasapl** [comment] 2022-01-25 20:44
I can install them in OCT7 (the 2u nodes), but I will also have to work out the network there since that rack is not currently connected.

**Comment by hakasapl** [comment] 2022-01-27 15:22
I was not able to install these because they require PSU power cables. The ones we have on hand are made for newer generation dell servers so they will not work. I'm working on ordering PSU cables.

**Comment by hakasapl** [comment] 2022-01-31 20:29
PSU power cables are being ordered and will be here for me to get these installed the week of the 7th.

**Comment by cooktheryan** [comment] 2022-02-14 14:42
@hakasapl I was just wondering if the cables came in

**Comment by hakasapl** [comment] 2022-02-17 03:39
GPUs are installed in three nodes (OCT7-19, OCT7-18, and OCT7-17), I will be in contact with @naved001 for getting into the network in that rack as a next step.

**Comment by hakasapl** [comment] 2022-02-17 15:16
Hi All,

Some bad news unfortunately. Last night after I had installed the three GPUs I decided to boot the first node so I could make sure the iDrac was set to DHCP and all that before I left.

Initially, the node did not boot at all, as in nothing happened when I pressed the power button.

I decided that this is most likely due to the PSU not having enough power for the P100 (currently a 750W). I swapped the PSUs out for 1100W models (Dell ones, so they are interchangeable with little effort).

When I powered on the server with the 1100W PSU, it started booting, but unfortunately with that a ton of smoke started billowing out of the exhaust of the server. I pulled the power and evacuated the building since the smoke alarm had been tripped.

Luckily, a fire hadn't actually started, just electrical smoke. Here is a picture of the damage on the server/GPU afterwards:

![IMG_0249](https://user-images.githubusercontent.com/40907639/154510179-8f1f17f3-23ba-4252-8919-78e43a1c3ba6.JPEG)

As you can see from the image, the smoke originated from where the card connected to the PCIe port.

While I haven't tested it yet, this GPU is almost certainly dead at this point, leaving only 2 remaining P100s.

At this point I'm not sure what the exact cause is. It could be:
* a short/fault on the GPU (were these tested before they were shipped here? I didn't see any damage related to shipping on that card, but there could have been an issue internally.)
* a fault on the PCIe bus the GPU was connected to (Going to reach out to Dell about it to get more information)

Either way, I am not comfortable booting the remaining two servers with GPUs in them at this point, and I am leaving them unplugged for now. I am in talks with the facility on the best way to go about this. I don't want to destroy another GPU so I want to figure out what happened with the first one. If I decide the fault was because of the individual GPU and not the node, then I will attempt to power on another node with a P100 outside the facility in case things go wrong again.

Let me know if you have any questions.

**Comment by hakasapl** [comment] 2022-02-17 15:28
A third possible cause:
* GPU wasn't slotted in all the way which caused some pins to short in the socket (The GPUs were slotted in as far as the PCIe bracket on the card let me push them in, so the bracket was flush with the chassis in the end, which all looks normal, but if for some reason the PCIe bracket on the GPU doesn't match the exact length of the chassis, maybe it was not slotted in all the way)

**Comment by TreeinRandomForest** [comment] 2022-02-21 13:01
@hakasapl thanks for the update. yep, it makes sense to find the root cause before booting the other gpu nodes and risking more damage.

**Comment by msdisme** [comment] 2022-03-07 19:48
Confirm supported config, then discuss with Kevin@mghpcc, needs to be done outside and run GPU stress test (on loading dock, when not raining, with fire extinguisher)

**Comment by cooktheryan** [comment] 2022-03-07 19:49
:rofl:

**Comment by msdisme** [comment] 2022-03-22 00:17
@durandom target is this week for testing and/or identifying alternative machines to host.

**Comment by msdisme** [comment] 2022-03-28 02:59
@hakasapl any updates on this ?

**Comment by hakasapl** [comment] 2022-03-28 19:38
Spoke with Kevin Helm at MGHPCC. The plan is in place to test out a working system with a GPU in it the week of the 11th of April. That being said, I was not able to identify a cause for why the first GPU burned, so I'd be testing with an identical setup (new server and gpu, but same configuration) under the assumption that either the server or the GPU had a fault.

My question: we also have some additional hardware coming in - would you prefer that I inquire about adding GPUs into those nodes instead of the R730 ones to avoid burning another GPU if for an unknown reason the R730s we have on hand are causing this? I just don't feel entirely confident that the same result won't happen on the second try.

Let me know your thoughts

**Comment by msdisme** [comment] 2022-04-06 18:47
@durandom please see note above- risk of damaging a second gpu.   If we are holding off for the new hardware it is 4 weeks till in the building and we would swap it into place

**Comment by msdisme** [comment] 2022-06-21 13:23
https://images.nvidia.com/content/grid/pdf/DA-09018-001_v08.pdf is a doc with supported hardware.  We are going to look through a list of donated equipment this week to ensure have a machine with adequate power/support for P100

**Comment by msdisme** [comment] 2023-01-03 19:10
We now have the hardware in that would support these, will be early february 2023 before we are able to address

**Comment by joachimweyl** [comment] 2023-06-20 16:40
SMAUG Cluster going away.

**Closed by joachimweyl** 2023-06-20 16:40 UTC
Labels: mghpcc
