### ISSUE TITLE
Bare Metal or Equivalent hw for RH Intern  starting May 23

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#573] opened 2022-05-18 01:24 UTC
Jason Schlessman (at EldritchJS) is working with a summer interns who will be working remote from Notre Dame on a project for image disinformation detection.  They will need access to a bare metal machine so they have enough compute power to run some of the image processing work.   If NERC was done, we would point them there, but since the intern starts May 23 and leaves in August, it won't be ready on time.

**Comment by msdisme** [comment] 2022-05-18 01:31
@naved001 not sure which larger bare metal systems are currently available. @EldritchJS any guidance on the RAM, storage etc. would be helpful.

**Comment by joachimweyl** [comment] 2022-06-03 14:42
@naved001 I remember a discussion that maybe they don't need bare metal. What are the next steps for them?

**Comment by naved001** [comment] 2022-06-08 13:48
> What are the next steps for them?

I don't know. That's a question for @msdisme. Currently we are only adding new users to our openshift cluster, because we plan to deprecate openstack.

**Comment by hpdempsey** [comment] 2022-06-08 14:07
The discussion about what they needed was that they DO need bare metal.  It does not need to be beefy.  Anything free will be better than the laptop.  (Anything except a Power9!)  :-)

**Comment by hpdempsey** [comment] 2022-06-08 14:09
Better to just do this than wait for more specifics unless the problem is that we don't have any machines--but that seems unlikely.

**Comment by hpdempsey** [comment] 2022-06-08 21:42
@EldritchJS you can't have an entire cluster.  That was why we discussed a bare metal node or nodes before.  If you want to use OpenShift, you can have access to run your project in pods on nodes in the existing Operate First or MOC OpenShift cluster, but the cluster is not going to be dedicated just to your project.  Or you can have a bare metal node(s) dedicated to your project and install any software you want (including OpenShift) on it.   It sounds like  you actually want to run your project in the regularl operational  OpenShift environment, with whatever nodes are available, so you just need to get an account to access Operate First of the Mass Open Cloud instead of a bare metal machine.  Sorry for the misunderstanding.

**Comment by EldritchJS** [comment] 2022-06-08 21:58
Ooops, my bad. I don't want to set up and admin an OpenShift cluster if I can help it! Sorry about that.

**Comment by hpdempsey** [comment] 2022-06-08 22:31
Jason and his research collaboartors will request regular accounts.

**Comment by msdisme** [comment] 2022-06-09 19:08
@msdisme - just checking, openshift of openstack?

**Comment by EldritchJS** [comment] 2022-06-09 19:11
@msdisme OpenShift :)

**Comment by msdisme** [comment] 2022-06-10 19:04
@EldritchJS could you please give us a file with admin and non-admin users as described below:

In the following instructions, usernames are the email addresses with
which people will be logging in - for this issue please use redhat.com addresses which are google and therefor may be used with our SSO.

### Using the web interface


1. Name the file `<yourprojectname>.yaml`, where `<yourprojectname>`
   is your desired project name. This name must:

   - Be all lower case
   - Be less than 55 characters in length
   - Contain only letters, numbers, `.` and `-`

  If this is for course related or internship projects the name should include the
  course number and year at the start of the name - eg.
  `rhintern-summer2022-eldritchjs`.

1. Create the body of the document.  The file is a YAML document that should look something like:

    ```
    description: Short description of your project
    requester: you@your.email.address
    quota: medium
    admins:
    - you@your.email.address
    users:
    - alice@example.com
    - bob@example.com
    ```

    You *must* include at least one admin user.


## About admins vs users

The `admin` and `user` entries map to the `admin` and `edit` OpenShift
[cluster roles]. The primary difference is that members of the `admin`
group are able to view and edit roles and role bindings.

[cluster roles]: https://docs.openshift.com/container-platform/4.8/authentication/using-rbac.html#default-roles_using-rbac

## About quotas

A [resource quota][] limits the aggregate resource consumption of a
project. Specifically, we use it to limit the CPU and memory
consumption of a project.

[resource quota]: https://kubernetes.io/docs/concepts/policy/resource-quotas/

When you create project, you may select from one of the following
quotas (note that these values were correct when this document was
written, by may drift over time. For authoritative information, see
<https://github.com/CCI-MOC/moc-project-tool/tree/master/quotas>):

- `x-small`

  - 1 CPU
  - 2G of RAM
  - 10GB of storage

- `small`

  - 1 CPU
  - 4G of RAM
  - 20GB of storage

- `medium`

  - 2 CPUS
  - 8G of RAM
  - 40GB of storage

- `large`

  - 4 CPUS
  - 16G of RAM
  - 80GB of storage

- `x-large`

  - 8 CPUS
  - 32G of RAM
  - 200GB of storage

If you need a resource allocation that doesn't match one of these
available quotas, please [open an issue][] with your specific request.

[open an issue]: https://osticket.massopen.cloud/open.php

**Comment by EldritchJS** [comment] 2022-06-13 15:01
I think the x-large size will work based on what the intern mentioned. 

Couple questions:

1. Safe to assume GPUs are not an option?
2. This is research which is part of an ongoing collaboration. Is it possible to have this be a more longterm project which I would take over the Red Hat side of the work from Fall forward? So instead of "rhintern-summer2022-eldritchjs"  maybe "disinformation-at-scale-eldritchjs" ?

Thanks!

**Comment by EldritchJS** [comment] 2022-06-13 17:03
@naved001  Great, so should I then make a custom quota that includes a GPU node?

**Comment by naved001** [comment] 2022-06-13 17:22
@EldritchJS yes, I think that'd be the way to go.

**Comment by EldritchJS** [comment] 2022-06-13 17:32
Not sure where to put the .yaml file, I attempted to attach to my quote but got an error msg saying .yaml isn't supported. Here's the yaml I created:

filename: ddas-eldritchjs.yaml
contents:

description: Disinformation Detection at Scale project to answer questions of scalability for dynamic disinformation detection.
requester: eldritchjs@redhat.com
quota: x-large
admins:
- eldritchjs@redhat.com
users:
- wtheisen@redhat.com



If I was to upload this somewhere else please let me know where. Also, I put in the x-large quota without mentioning the GPU as the instructions give me the impression the project is to be started and then a custom quota can be specified in an issue. If I could be advised on how to proceed I'd greatly appreciate it. Thanks!

**Comment by naved001** [comment] 2022-06-13 17:36
@EldritchJS a custom quota looks like this: https://github.com/CCI-MOC/moc-apps/pull/143/files#diff-30a1f96ad6958c7629a78b3ec3c685d378cd9b5b2c4bdad31d9dae7e10be1e93

Instead of sharing a yaml here, you could submit a PR to that repo (with the quota you need including the GPU), then I can merge it after I create your project.

**Comment by naved001** [comment] 2022-06-13 17:37
@EldritchJS I'll call your project/namespace `disinformation-at-scale-eldritchjs`

**Comment by EldritchJS** [comment] 2022-06-13 17:41
Thanks @naved001 

So I'll submit a PR to https://github.com/CCI-MOC/moc-apps  with my yaml file.

Can you let me know what directory you'd like the disinformation-at-scale-eldritchjs.yaml to be in?

**Comment by EldritchJS** [comment] 2022-06-13 18:29
Thanks @naved001 

I've just determined I cannot log on to https://k-openshift.osh.massopen.cloud:8443/ with sso_auth. I was trying to log in so I could  get/describe nodes to try to determine if the nvidia operator is running on the cluster, so I'd have a better idea of how to specify the GPU in my quota yamls. 

When I attempt to log in to the openshift dashboard I enter my sso credentials and token, and I get a response page of `Could not find user.` 

One thing I should note: eldritchjs@redhat.com is an email alias. My original issued Red Hat account is jschless@redhat.com in case that needs to be my openshift account info. 


Sorry for all the stumbling, thank you for all your help!

**Comment by naved001** [comment] 2022-06-13 18:35
@EldritchJS the openshift cluster is available at: https://console-openshift-console.apps.ocp-prod.massopen.cloud/dashboards and you should be able to login to that now with your redhat credentials.

what you linked is our older OpenShift 3 cluster.

**Comment by naved001** [comment] 2022-06-13 18:40
the GPU node has the label `nvidia.com/gpu.present=true`, so something with that? not super sure really.

maybe we can do whatever the documentation here says: https://kubernetes.io/docs/concepts/policy/resource-quotas/#resource-quota-for-extended-resources

**Comment by EldritchJS** [comment] 2022-06-13 19:11
Thanks, the email I initially received after the request was approved sent me to that other cluster. The one you pointed me to lets me log in just fine!

If the nvidia gpu operator is running then what you linked to should work. Since the node has nvidia.com/gpu.present that hopefully indicates it's running, so I changed my quota files accordingly. 

Here's my PR :crossed_fingers: https://github.com/CCI-MOC/moc-apps/pull/177

**Comment by EldritchJS** [comment] 2022-06-14 15:21
@naved001 

Glad the merge was approved!

Should I expect to see the project in the openshift dashboard now? I'm logged in as jschless@redhat.com and am wondering (again) if I screwed up using eldritchjs@redhat.com earlier in this issue since my SSO account name is jschless@redhat.com

Thanks for all your help!

**Comment by naved001** [comment] 2022-06-14 15:32
I don't know the answer about the SSO names. @knikolla / @larsks do either of you know?

**Comment by larsks** [comment] 2022-06-14 15:40
@naved001 the name you log in with matters: user `eldritchjs@redhat.com` is a member of the `disinformation-at-scale-eldritchjs-admin` group, but `jschless@redhat.com` is not. We will need to update the project configuration (add `jschless@redhat.com` as an admin).

**Comment by EldritchJS** [comment] 2022-06-14 17:03
@naved001 I can see the project now, thank you so much!

**Comment by naved001** [comment] 2022-06-14 17:18
@EldritchJS Awesome! I am going to close this issue here. If you run into any other problems please open a ticket at [osticket.massopen.cloud](https://osticket.massopen.cloud/)

**Closed by naved001** 2022-06-14 17:18 UTC
Labels: added_post_planning, accepted, size/small, needs_clarification

**Comment by msdisme** [comment] 2022-10-11 08:23
Just approved one

---
Michael Daitzman (He/Him)
***@***.***
cell:978-201-9965



From: Heidi Picher Dempsey ***@***.***>
Date: Wednesday, June 8, 2022 at 6:32 PM
To: CCI-MOC/ops-issues ***@***.***>
Cc: Daitzman, Michael S ***@***.***>, State change ***@***.***>
Subject: Re: [CCI-MOC/ops-issues] Bare Metal or Equivalent hw for RH Intern starting May 23 (Issue #573)

Jason and his research collaboartors will request regular accounts.
