### ISSUE TITLE
Investigate tools for keeping available labels in sync across our repositories.

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#110] opened 2021-01-07 15:19 UTC
We would like some labels (e.g. "added_after_sprint") to be available in all repositories so that we can use them during sprint planning.

**Comment by joachimweyl** [comment] 2022-10-26 15:35
duplicate of https://github.com/CCI-MOC/ops-issues/issues/270

**Closed by joachimweyl** 2022-10-26 15:35 UTC
Labels: duplicate
