### ISSUE TITLE
Evaluate what InstructLab deployment to OpenShift in MOC will require

### ISSUE THREAD

**Issue by hpdempsey** [CCI-MOC/ops-issues#1297] opened 2024-04-24 14:21 UTC
InstructLab is now available in open source (https://github.com/instructlab), along with the Granite model that it uses:  (https://huggingface.co/instructlab).  The training data sets and training methodology for the Granite model are not available yet, but we expect them to become so.  We should begin to evaluate requirements for building a cluster that could make this available to MOC/NERC users.   Our goal is that researchers and students should eventually be able to use InstructLab for text-based workflows that would help them with their domain research and teaching projects.

**Comment by hpdempsey** [comment] 2024-04-24 14:22
This will eventually be an epic, but opening this issue to track the early review and analysis of available code and systems.

**Comment by hpdempsey** [comment] 2024-04-24 14:39
Some initial steps:

1) Identify available hardware and storage dependencies (GPUs, CPUs, NESE Ceph)
2) Identify software version dependencies in existing deployments (OpenShift AI, OpenShift, RHEL) and any new software and operators that will be needed.
3) Identify any new tools required for building this cluster

**Comment by larsks** [comment] 2024-05-01 14:25
I'm working on coming up to speed on all the parts here.

The default instructlab distribution is designed to run on laptops and other devices with modest resources. Just about all of the instructlab repositories include this note:

> It is important to understand that running InstructLab on a laptop will give you a low-fidelity approximation of both synthetic data generation (using the ilab generate command) and model instruction tuning (using the ilab train command, which uses QLoRA.) The quality of the results you get using these tools on a laptop will not be as high-fidelity as they might be using a larger teacher model and a different training method. We have optimized InstructLab to enable community members with modest hardware to be able to use the technique. If you have more sophisticated hardware, you can configure InstructLab to use a larger teacher model such as Mixtral in order to achieve higher-fidelity results.

I am trying to wrap my head around the resource requirements for running something like [Mixtral 8x7B](https://mistral.ai/news/mixtral-of-experts/). The blog post from mistral.ai doesn't really address that question.  The best information I've found so far is [this article](https://neon.tech/blog/mixtral-8x7b-what-you-need-to-know-about-mistral-ais-latest-model), which says:

> If you plan to fine-tune Mixtral and your own inference, it’s important to note that Mixtral requires much more RAM and GPUs than Mistral 7B. While Mistral 7B works well on a 24GB RAM 1 GPU instance, Mixtral requires 64GB of RAM and 2 GPUs, which increases the cost by a factor of 3 (1.3$/h vs. 4.5$/h).

We don't really know what's required to run the upstream InstructLab models, since they haven't yet been released.

**Comment by joachimweyl** [comment] 2024-08-07 16:38
duplicate of https://github.com/nerc-project/operations/issues/628

**Closed by joachimweyl** 2024-08-07 16:38 UTC
Labels: duplicate

**Comment by hpdempsey** [comment] 2024-12-05 23:27
Update, per a request from Milson.   The version of InstructLab that has been changed to support deployment in the MOC environment (as opposed to a single laptop or server) is getting close to finished in the test cluster.   Red Hat will be working on moving this from dev preview to a production release through the RHELAI product.  @DanNiESh is currently working on the build pipeline for this in the MOC.   She and @tssala23 will be working on making it available as an MOC release for students and researcher community.   @Milson would like to be able to share and demo this when it is running successfully in a test cluster with the config files etc. available.
